export const primaryTheme =
{
    ACTIVE_LINK_COLOR: '#F26620',
    HOVER_LINK_COLOR: '#F26620',
    NOTIFICATION_BACKGROUND: '#F26620',
    MENU_BACKGROUND_COLOR: '#F3F3F3',
    MENU_BACKGROUND_SHADOW: 'rgba(0, 0, 0, 0.25)',
    PROFILE_WIDTH_AND_HEIGHT: '50px',
    LINK_PADDING: '10px',
    LINK_WRAPPER_PADDING: '35px',
    CARD_BORDER_RADIUS: '7px',
    CARD_ITEM_PADDING: '16px 10px',
}